sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 6
matrix:
    fast_finish: true
script: npm run travis
before_install:
  - npm i -g npm
after_success:
  - npx semantic-release
